{
 "title": "hpa cpu record",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(cpu_current_replicas{}, cluster)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(cpu_current_replicas{}, app)"
    }
   },
   {
    "name": "appCode",
    "label": "appCode",
    "query": {
     "query": "label_values(cpu_current_replicas{app=\"$app\"}, appCode)"
    }
   },
   {
    "name": "projectCode",
    "label": "projectCode",
    "query": {
     "query": "label_values(cpu_current_replicas{app=\"$app\"}, projectCode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "min_replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_min_replicas{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}"
    }
   ]
  },
  {
   "title": "current_replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_current_replicas{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}"
    }
   ]
  },
  {
   "title": "max_replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_max_replicas{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}"
    }
   ]
  },
  {
   "title": "metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "cpu_target_value{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}",
     "legendFormat": "target_cpu"
    },
    {
     "expr": "cpu_current_value{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}",
     "legendFormat": "current_cpu"
    }
   ]
  },
  {
   "title": "current_replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "cpu_current_replicas{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}",
     "legendFormat": "current_replicas"
    },
    {
     "expr": "cpu_max_replicas{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}",
     "legendFormat": "max_replicas"
    },
    {
     "expr": "cpu_min_replicas{app=\"$app\",appCode=\"$appCode\",projectCode=\"$projectCode\"}",
     "legendFormat": "min_replicas"
    }
   ]
  }
 ]
}