{
 "title": "cpu-hpa-record",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(cpu_current_replicas{}, cluster)"
   },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(cpu_current_replicas{}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "min_replicas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cpu_min_replicas{cluster=\"$cluster\",app=\"$app\"}"
    }
   ]
  },
  {
   "title": "current_replicas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cpu_current_replicas{cluster=\"$cluster\",app=\"$app\"}"
    }
   ]
  },
  {
   "title": "max_replicas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cpu_max_replicas{cluster=\"$cluster\",app=\"$app\"}"
    }
   ]
  },
  {
   "title": "metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_target_value{cluster=\"$cluster\",app=\"$app\"}",
     "legendFormat": "target_cpu"
    },
    {
     "expr": "cpu_current_value{cluster=\"$cluster\",app=\"$app\"}",
     "legendFormat": "current_cpu"
    },
    {}
   ]
  },
  {
   "title": "replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_current_replicas{cluster=\"$cluster\",app=\"$app\"}",
     "legendFormat": "current_replicas"
    },
    {
     "expr": "cpu_max_replicas{cluster=\"$cluster\",app=\"$app\"}",
     "legendFormat": "max_replicas"
    },
    {
     "expr": "cpu_min_replicas{cluster=\"$cluster\",app=\"$app\"}",
     "legendFormat": "min_replicas"
    }
   ]
  }
 ]
}