{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hparecord.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hparecord.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hparecord.selectorLabels" . | nindent 8 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - path: /metrics
      port: http
      metricRelabelings:
        - action: labeldrop
          regex: namespace
        - action: labeldrop
          regex: pod
        - action: labeldrop
          regex: instance
        - action: labeldrop
          regex: service
        - action: labeldrop
          regex: endpoint
{{- end }}